### ISSUE TITLE
Add functionality to alter dates

### ISSUE THREAD

**Issue by NS21fpsy** [humdek-unibe-ch/sh-shp-formula_parser#2]
I'm trying to define the end of a time range based on a dynamic starting date.

example for formula:
https://dropit.psy.unibe.ch/admin/cms_update/97/update/prop

Maybe the formula parser can support something like strtotime() or date_add() ?

I'm trying formulas like:

date('Y-m-d', strtotime('{{first_entry_date_formatted}}'. ' + 7 days'))
or
date_add('{{first_entry_date_formatted}}', date_interval_create_from_date_string("7 days"))

but I can't generate the new date that I want.

**Comment by Kodzhabashev** [comment]
It is not possible right now. But this can be added.

**Comment by Kodzhabashev** [comment]
Implemented in v1.4.3
