### ISSUE TITLE
New formula: "isUserInGroup"

### ISSUE THREAD

**Issue by NS21fpsy** [humdek-unibe-ch/sh-shp-formula_parser#8]
Could you add a function like "isUserInGroup" that would take a string (group name) and return true or false?

With that, we could pass the info about the group membership into the question builders like labJS.

Thanks!

**Comment by Kodzhabashev** [comment]
That makes sense

Will it be useful to add also a function getUserGroups(), that can return an array with all the groups in which the user is?

**Comment by NS21fpsy** [comment]
This could certainly be useful.

Whether it is easy to work with an array in a question builder is another question. It would certainly be helpful for the work in the Question Builder tools if we could somehow spread the values from the array into our own variable holders. So each group would be in its own variable. Do you know what I mean?

**Comment by Kodzhabashev** [comment]
Then i can add also the implode function. In this case you can have the groups in array and if needed you can convert them to a string?

**Comment by NS21fpsy** [comment]
nice, thanks

**Comment by Kodzhabashev** [comment]
Implemneted in v1.5.1 - Requires SelfHelp v6.16.4+
